{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8e1562b3-8c64-4462-80ea-43888a03af53",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for cadquery Workplane and Shape\n",
      "\n",
      "Enabling jupyter_cadquery replay\n",
      "Note: To get rid of this warning, use 'enable_replay(False)'\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "   Copyright 2023 Raphaël Isvelin\n",
    "\n",
    "   Licensed under the Apache License, Version 2.0 (the \"License\");\n",
    "   you may not use this file except in compliance with the License.\n",
    "   You may obtain a copy of the License at\n",
    "\n",
    "       http://www.apache.org/licenses/LICENSE-2.0\n",
    "\n",
    "   Unless required by applicable law or agreed to in writing, software\n",
    "   distributed under the License is distributed on an \"AS IS\" BASIS,\n",
    "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
    "   See the License for the specific language governing permissions and\n",
    "   limitations under the License.\n",
    "\"\"\"\n",
    "\n",
    "VIEWER_THEME = \"light\"  # light, dark\n",
    "VIEWER_HEIGHT = 900\n",
    "ENABLE_REPLAY = True\n",
    "\n",
    "import cadquery as cq\n",
    "\n",
    "from jupyter_cadquery import show as jcq_show\n",
    "from jupyter_cadquery import (\n",
    "    versions,\n",
    "    PartGroup, Part, \n",
    "    get_viewer, close_viewer, get_viewers, close_viewers, open_viewer, set_defaults, get_defaults, open_viewer, get_pick,\n",
    ")\n",
    "\n",
    "from jupyter_cadquery.replay import replay, enable_replay, disable_replay\n",
    "enable_replay(ENABLE_REPLAY)\n",
    "\n",
    "from cq_warehouse.fastener import (\n",
    "    polygon_diagonal,\n",
    "    read_fastener_parameters_from_csv,\n",
    "    Screw, SocketHeadCapScrew, HeatSetNut, PlainWasher,\n",
    "    HexNutWithFlange, HexHeadScrew, PanHeadScrew, CounterSunkScrew\n",
    ")\n",
    "import cq_warehouse.extensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d78d34c-12d6-4ddd-b5f4-5e649a25570e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ca8c0003-008c-41ae-b296-10d85e0fda89",
   "metadata": {},
   "outputs": [],
   "source": [
    "cv = open_viewer(\"Assembly\", anchor=\"right\")  # sets default viewer\n",
    "\n",
    "objects_to_hide = [\n",
    "    \"/Masks\"\n",
    "]\n",
    "\n",
    "def hide_objects_matching_strings(strings, keep_edges=True, cv=cv):\n",
    "    for state in cv.widget.states:\n",
    "        should_hide = False\n",
    "        for s in strings:\n",
    "            if s in state:\n",
    "                should_hide = True\n",
    "                break\n",
    "        if should_hide:\n",
    "            cv.update_states({\n",
    "                state: (0, 0 if keep_edges else 0),\n",
    "            })\n",
    "            \n",
    "def show(obj, viewer=\"Assembly\", anchor=\"right\", hide_contains=objects_to_hide):\n",
    "    cv = jcq_show(\n",
    "        obj,\n",
    "        viewer=viewer,\n",
    "        anchor=anchor,\n",
    "        #cad_width=1640,\n",
    "        height=VIEWER_HEIGHT,\n",
    "        theme=VIEWER_THEME,\n",
    "        collapse=1,\n",
    "        optimal_bb=True,\n",
    "        render_edges=True,\n",
    "        axes=True,\n",
    "        axes0=True,\n",
    "        grid=[True, True, True],\n",
    "        #black_edges=True,\n",
    "        reset_camera=False,\n",
    "        #show_parent=True,\n",
    "        #timeit=True,\n",
    "        #js_debug=True\n",
    "    )\n",
    "    hide_objects_matching_strings(hide_contains, cv=cv)\n",
    "\n",
    "def show_b(obj, viewer=\"Quick\", hide_contains=objects_to_hide):\n",
    "    cv2 = open_viewer(viewer, anchor=\"split-bottom\")\n",
    "    show(obj, viewer, anchor=\"split-bottom\", hide_contains=hide_contains)\n",
    "\n",
    "def show_x(obj, hide_contains=objects_to_hide):\n",
    "    show(obj, viewer=None, hide_contains=hide_contains)\n",
    "\n",
    "def show_part(part: Part, bottom=False):\n",
    "    footprint_assembly = (\n",
    "        cq.Assembly()\n",
    "            .add(part.debug_objects.footprint.inside, name=\"Inside\", color=cq.Color(1, 0, 1))\n",
    "            .add(part.debug_objects.footprint.outside, name=\"Outside\", color=cq.Color(0, 1, 1))\n",
    "    )\n",
    "    test_assembly = (\n",
    "        cq.Assembly(None, name=\"test_assembly\")\n",
    "            .add(part.mask, name=\"Mask\", color=cq.Color(0, 1, 0))\n",
    "            .add(part.part, name=\"Part\")\n",
    "            .add(part.assembly_parts_to_cq_assembly(), name=\"Part assembly\")\n",
    "            .add(footprint_assembly, name=\"Footprint\")\n",
    "    )\n",
    "    debug_assembly = cq.Assembly()\n",
    "    debug_assembly.add(part.debug_objects.hole, name=\"Hole\", color=cq.Color(1, 0, 0))\n",
    "    for debug_obj_name in part.debug_objects.others.keys():\n",
    "        obj = part.debug_objects.others[debug_obj_name]\n",
    "        if not isinstance(obj, dict):\n",
    "            debug_assembly.add(obj, name=debug_obj_name, color=cq.Color(0.5, 0.7, 0.5))\n",
    "    test_assembly.add(debug_assembly, name=\"Debug\")\n",
    "\n",
    "    if bottom: show_b(test_assembly)\n",
    "    else: show(test_assembly)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1203c2de-a14d-4b63-b8ad-f2627d3dfd40",
   "metadata": {},
   "source": [
    "## Build test parts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5e2149ef-cf0b-4fd8-bd99-f3e60144e4f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "VALIDATING CLASS: EncoderEc11Part\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "TODO Need to move all workplanes so the hole's center is at 0,0\n",
      "VALIDATING CLASS: Hdmi5InchJrp5015Part\n",
      "VALIDATING CLASS: PotentiometerWh148Part\n",
      "VALIDATING CLASS: Banana4mmPart\n",
      "VALIDATING CLASS: BarrelPlugDc022bPart\n",
      "VALIDATING CLASS: RcaN1030Part\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (12/12)  0.16s\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"../src\")\n",
    "\n",
    "from cq_enclosure_builder import PartFactory as pf\n",
    "from cq_enclosure_builder import Panel, PanelSize\n",
    "from cq_enclosure_builder import Enclosure, Face\n",
    "from cq_enclosure_builder.knobs_and_caps import KNOB_12_6_x_15_8\n",
    "\n",
    "pf.set_default_types({\n",
    "    \"jack\": '6.35mm PJ-612A',\n",
    "    \"usb_a\": '3.0 vertical cltgxdd',\n",
    "    \"usb_c\": 'ChengHaoRan E',\n",
    "    \"button\": 'SPST PBS-24B-4',\n",
    "    \"encoder\": 'EC11',\n",
    "    \"screen\": 'HDMI 5 inch JRP5015',\n",
    "    \"potentiometer\": 'WH148',\n",
    "    \"banana\": '4mm',\n",
    "    \"barrel_plug\": 'DC-022B',\n",
    "    \"rca\": 'N1030',\n",
    "})\n",
    "pf.set_default_parameters({\n",
    "    \"enclosure_wall_thickness\": 2,\n",
    "    \"pot_knob\": KNOB_12_6_x_15_8\n",
    "})\n",
    "\n",
    "usb_c = pf.build_usb_c()\n",
    "usb_c_v = pf.build_usb_c(orientation_vertical=True)\n",
    "usb_a = pf.build_usb_a()\n",
    "usb_a_v = pf.build_usb_a(orientation_vertical=True)\n",
    "spst = pf.build_button()\n",
    "encoder = pf.build_encoder() \n",
    "jack_35 = pf.build_jack(part_type='3.5mm XXX')\n",
    "jack_635 = pf.build_jack()\n",
    "screen = pf.build_screen()\n",
    "pot = pf.build_potentiometer()\n",
    "banana = pf.build_banana()\n",
    "barrel_plug = pf.build_barrel_plug()\n",
    "rca = pf.build_rca()\n",
    "\n",
    "\n",
    "show_part(pot)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b01182c8-4cc9-4056-a9cc-04fad38043f2",
   "metadata": {},
   "source": [
    "## Panels etc."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "011258ac-a9d9-4c17-901a-0772125e9e1b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "70c8b066-3432-4ef0-a0d6-a3513bbd5a79",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "from cq_enclosure_builder import Face\n",
    "from cq_enclosure_builder.part import Part\n",
    "\n",
    "class PanelSize:\n",
    "    def __init__(self, width, length, wall_thickness, total_thickness):\n",
    "        self.width = width\n",
    "        self.length = length\n",
    "        self.wall_thickness = wall_thickness\n",
    "        self.total_thickness = total_thickness\n",
    "\n",
    "class Panel:\n",
    "    def __init__(self,\n",
    "                 face: Face,\n",
    "                 top_view_width,\n",
    "                 top_view_length,\n",
    "                 wall_thickness,\n",
    "                 color=None,\n",
    "                 part_color=None,\n",
    "                 alpha=1.0,\n",
    "                 lid_size_error_margin=0.0  # if provided, panel will be smaller than mask\n",
    "        ):\n",
    "        self.face = face\n",
    "        self.size = PanelSize(top_view_width, top_view_length, wall_thickness, wall_thickness)\n",
    "        self._color = color\n",
    "        if self._color == None:\n",
    "            self._color = self.face.default_color\n",
    "        self._part_color = part_color\n",
    "        if self._part_color == None:\n",
    "            self._part_color = self.face.default_part_color\n",
    "        self.panel = None\n",
    "        self.mask = self._rotate_to_face(\n",
    "            cq.Workplane(\"front\")\n",
    "                .workplane()\n",
    "                .box(top_view_width, top_view_length, wall_thickness, centered=(True, True, False))\n",
    "        )\n",
    "        self.debug_assemblies = {}\n",
    "        self.debug_assemblies[\"hole\"] = None\n",
    "        self.debug_assemblies[\"footprint_in\"] = None\n",
    "        self.debug_assemblies[\"footprint_out\"] = None\n",
    "        self.debug_assemblies[\"other\"] = None\n",
    "        self.debug_assemblies[\"combined\"] = cq.Assembly(None, name=self.face.label + \" - Debug\")\n",
    "        self.lid_size_error_margin = lid_size_error_margin\n",
    "        self._alpha = alpha\n",
    "        self._parts_to_add = []\n",
    "\n",
    "    def add(self, label: str, part: Part, rel_pos=None, abs_pos=None):\n",
    "        print(self.face.label + \": adding part '\" + label + \"'\")\n",
    "        pos = None\n",
    "        if rel_pos == None and abs_pos == None:\n",
    "            raise ValueError(\"Either rel_pos or abs_pos must be set.\")\n",
    "        elif rel_pos == None:\n",
    "            pos = (\n",
    "                abs_pos[0] - self.size.width/2,\n",
    "                abs_pos[1] - self.size.length/2\n",
    "            )\n",
    "        elif abs_pos==None:\n",
    "            pos = rel_pos\n",
    "        self._parts_to_add.append({\n",
    "            \"part\": part,\n",
    "            \"label\": label,\n",
    "            \"pos\": pos\n",
    "        })\n",
    "        return self\n",
    "\n",
    "    def assemble(self):\n",
    "        wall = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .workplane()\n",
    "                .box(self.size.width - self.lid_size_error_margin, self.size.length - self.lid_size_error_margin, self.size.wall_thickness,\n",
    "                     centered=(True, True, False))\n",
    "        )\n",
    "        self.panel = cq.Assembly(None, name=\"Panel TOP\")\n",
    "        for part_to_add in self._parts_to_add:\n",
    "            part_obj = part_to_add[\"part\"]\n",
    "            self._add_part_to_debug_assemblies(part_to_add)\n",
    "            wall = wall.cut(\n",
    "                part_obj.mask.translate([*part_to_add[\"pos\"], 0])\n",
    "            )\n",
    "            if part_obj.assembly_parts != None:\n",
    "                self.panel = self.panel.add(\n",
    "                    self._translate_assembly_objects_and_rotate_to_face(part_obj.assembly_parts, [*part_to_add[\"pos\"], 0]))\n",
    "                    #self._rotate_assembly_to_face(part_obj.part_assembly.translate([*part_to_add[\"pos\"], 0])))\n",
    "            else:\n",
    "                self.panel = self.panel.add(\n",
    "                    self._rotate_to_face(\n",
    "                        part_obj.part.translate([*part_to_add[\"pos\"], 0])),\n",
    "                    name=part_to_add[\"label\"],\n",
    "                    color=cq.Color(*self._part_color, 1.0)\n",
    "                )\n",
    "            if part_obj.size.thickness > self.size.total_thickness:\n",
    "                self.size.total_thickness = part_obj.size.thickness\n",
    "        self.panel = self.panel.add(self._rotate_to_face(wall), name=\"Wall\", color=cq.Color(*self._color, self._alpha))\n",
    "        self.debug_assemblies[\"combined\"] = self._build_combined_debug_assembly()\n",
    "        return self\n",
    "\n",
    "    def _rotate_to_face(self, wp):\n",
    "        if self.face == Face.TOP:\n",
    "            wp = wp.mirror(\"XY\")\n",
    "        elif self.face == Face.BOTTOM:\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.BACK:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.mirror(\"YZ\")\n",
    "        elif self.face == Face.FRONT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.LEFT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.rotate((0, 0, 0), (0, 0, 1), 90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.RIGHT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.rotate((0, 0, 0), (0, 0, 1), -90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        return wp\n",
    "\n",
    "    def _translate_assembly_objects_and_rotate_to_face(self, assembly_parts, translation):\n",
    "        assembly = cq.Assembly()\n",
    "        for assembly_part in assembly_parts:\n",
    "            part, loc, name, color = assembly_part.as_assembly_add_parameters()\n",
    "            part = part.translate(translation)\n",
    "            part = self._rotate_to_face(part)\n",
    "            assembly.add(part, name=name, color=color)\n",
    "        return assembly\n",
    "\n",
    "    def _add_part_to_debug_assemblies(self, part_to_add):\n",
    "        part = part_to_add[\"part\"]\n",
    "        part_pos = part_to_add[\"pos\"]\n",
    "        part_label: str = part_to_add[\"label\"]\n",
    "        if part.debug_objects.hole != None:\n",
    "            if self.debug_assemblies[\"hole\"] == None:\n",
    "                self.debug_assemblies[\"hole\"] = cq.Assembly()\n",
    "            hole = self._rotate_to_face(part.debug_objects.hole.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"hole\"] = self.debug_assemblies[\"hole\"].add(hole, name=part_label, color=cq.Color(1, 0, 0))\n",
    "        if part.debug_objects.footprint.inside != None:\n",
    "            if self.debug_assemblies[\"footprint_in\"] == None:\n",
    "                self.debug_assemblies[\"footprint_in\"] = cq.Assembly()\n",
    "            footprint_in = self._rotate_to_face(part.debug_objects.footprint.inside.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"footprint_in\"] = self.debug_assemblies[\"footprint_in\"].add(footprint_in, name=part_label, color=cq.Color(1, 0, 1))\n",
    "        if part.debug_objects.footprint.outside != None:\n",
    "            if self.debug_assemblies[\"footprint_out\"] == None:\n",
    "                self.debug_assemblies[\"footprint_out\"] = cq.Assembly()\n",
    "            footprint_out = self._rotate_to_face(part.debug_objects.footprint.outside.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"footprint_out\"] = self.debug_assemblies[\"footprint_out\"].add(footprint_out, name=part_label, color=cq.Color(0, 1, 1))\n",
    "        other_debug_assembly = None\n",
    "        for key in part.debug_objects.others.keys():\n",
    "            if other_debug_assembly == None:\n",
    "                other_debug_assembly = cq.Assembly(None)\n",
    "                self.debug_assemblies[\"other\"] = cq.Assembly()\n",
    "            debug_part = self._rotate_to_face(part.debug_objects.others[key].translate([*part_pos, 0]))\n",
    "            other_debug_assembly = other_debug_assembly.add(debug_part, name=key)\n",
    "        if other_debug_assembly != None:\n",
    "            if self.debug_assemblies[\"other\"] == None:\n",
    "                self.debug_assemblies[\"other\"] = cq.Assembly()\n",
    "            self.debug_assemblies[\"other\"] = self.debug_assemblies[\"other\"].add(other_debug_assembly, name=part_label, color=cq.Color(1, 1, 0))\n",
    "\n",
    "    def _build_combined_debug_assembly(self):\n",
    "        combined = self.debug_assemblies[\"combined\"]\n",
    "        combined = combined.add(self.mask, name=\"Mask\", color=cq.Color(0, 1, 0, 0.5))\n",
    "        if self.debug_assemblies[\"hole\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"hole\"], name=\"Holes\")\n",
    "        if self.debug_assemblies[\"footprint_in\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"footprint_in\"], name=\"Footprint in\")\n",
    "        if self.debug_assemblies[\"footprint_out\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"footprint_out\"], name=\"Footprint out\")\n",
    "        if self.debug_assemblies[\"other\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"other\"], name=\"Other\")\n",
    "        return combined\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9c235a8e-c687-4873-acea-7e6c4c648556",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Building CS cat m3 - ref M3-0.5\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (4/4)  0.28s\n"
     ]
    }
   ],
   "source": [
    "from cq_enclosure_builder.parts.common.screw_block import ScrewBlock\n",
    "from cq_enclosure_builder.parts.common.screws_providers import DefaultFlatHeadScrewProvider, DefaultHeadSetScrewProvider\n",
    "\n",
    "screw = ScrewBlock(screw_provider=DefaultFlatHeadScrewProvider,\n",
    "                   counter_sunk_screw_provider=DefaultFlatHeadScrewProvider\n",
    "        ).m3(6, is_counter_sunk=True, with_counter_sunk_block=True)\n",
    "\n",
    "a = (\n",
    "    cq.Assembly(None, name=\"Screw block\")\n",
    "        .add(screw[\"block\"], name=\"Block\", color=cq.Color(1, 0, 0))\n",
    "        .add(screw[\"mask\"], name=\"Block Mask\", color=cq.Color(0, 1, 0))\n",
    "        .add(screw[\"counter_sunk_block\"], name=\"CS Block\", color=cq.Color(0, 1, 1))\n",
    "        .add(screw[\"counter_sunk_mask\"], name=\"CS Block Mask\", color=cq.Color(0, 1, 0))\n",
    ")\n",
    "show(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "id": "1f5e3a2c-0f4f-4cb6-b035-17cd448bbe18",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "from typing import List\n",
    "\n",
    "from cq_enclosure_builder.parts.common.screw_block import ScrewBlock, TaperOptions\n",
    "from cq_enclosure_builder.parts.common.screws_providers import DefaultFlatHeadScrewProvider, DefaultHeadSetScrewProvider\n",
    "\n",
    "def explode(pos_array, walls_explosion_factor=2.0):\n",
    "    return [x * walls_explosion_factor for x in pos_array]\n",
    "\n",
    "class EnclosureSize:\n",
    "    def __init__(self, inner_width, inner_length, inner_thickness, wall_thickness):\n",
    "        self.inner_width = inner_width\n",
    "        self.inner_length = inner_length\n",
    "        self.inner_thickness = inner_thickness\n",
    "        self.wall_thickness = wall_thickness\n",
    "\n",
    "class Enclosure:\n",
    "    def __init__(\n",
    "        self,\n",
    "        size: EnclosureSize,\n",
    "        lid_on_faces: List[Face] = [Face.BOTTOM],\n",
    "        lid_panel_size_error_margin = 0.8,  # meaning the lid is `margin` smaller than the hole on both width and length\n",
    "        lid_screws_thickness_error_margin = 0.4,\n",
    "        add_corner_lid_screws = True,\n",
    "        no_fillet_top = False,\n",
    "        no_fillet_bottom = False,\n",
    "        \n",
    "    ):\n",
    "        super().__init__()\n",
    "\n",
    "        inner_width = size.inner_width\n",
    "        inner_length = size.inner_length\n",
    "        inner_thickness = size.inner_thickness\n",
    "        wall_thickness = size.wall_thickness\n",
    "        self.size = size\n",
    "        self.no_fillet_top = no_fillet_top\n",
    "        self.no_fillet_bottom = no_fillet_bottom\n",
    "\n",
    "        if lid_on_faces != [Face.BOTTOM]:\n",
    "            # TODO: add support (upddate the correct face in panels_specs)\n",
    "            # TODO nice-to-have: also add support for multiple lids (faces)\n",
    "            raise ValueError(\"lid_on_faces: only value supported for now is [BOTTOM], got \" + str(lid_on_faces))\n",
    "\n",
    "        self.frame = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(inner_width - 4, inner_length - 4, inner_thickness - 4, centered=(True, True, False))\n",
    "                #.faces(\"+Z\")\n",
    "                .shell(wall_thickness)\n",
    "                #.translate([2, 2, 2])\n",
    "        )\n",
    "        self.panels_specs = [\n",
    "            (Face.TOP,    (inner_width-4,  inner_length-4,    wall_thickness),  [0, 0, inner_thickness - wall_thickness],   0.9 ),\n",
    "            (Face.BOTTOM, (inner_width-4,  inner_length-4,    wall_thickness),  [0, 0, -wall_thickness],    0.9 ),\n",
    "            (Face.FRONT,  (inner_width-4,  inner_thickness-4, wall_thickness),  [0, -(inner_length/2), inner_thickness/2 - wall_thickness], 0.9 ),\n",
    "            (Face.BACK,   (inner_width-4,  inner_thickness-4, wall_thickness),  [0, inner_length/2, inner_thickness/2 - wall_thickness],  0.9 ),\n",
    "            (Face.LEFT,   (inner_length-4, inner_thickness-4, wall_thickness),  [-(inner_width/2), 0, inner_thickness/2 - wall_thickness], 0.9 ),\n",
    "            (Face.RIGHT,  (inner_length-4, inner_thickness-4, wall_thickness),  [inner_width/2, 0, inner_thickness/2 - wall_thickness],  0.9 ),\n",
    "        ]\n",
    "\n",
    "        self.panels = {}\n",
    "        self.screws_specs = []\n",
    "        self.screws = []\n",
    "\n",
    "        for info in self.panels_specs:\n",
    "            lid_size_error_margin = 0 if info[0] not in lid_on_faces else lid_panel_size_error_margin\n",
    "            self.panels[info[0]] = Panel(info[0], *info[1], alpha=info[3], lid_size_error_margin=lid_size_error_margin)\n",
    "\n",
    "        if add_corner_lid_screws:\n",
    "            self.add_corner_lid_screws(lid_screws_thickness_error_margin)\n",
    "\n",
    "    def add_part_to_face(self, face: Face, part_label: str, part: Part, rel_pos=None, abs_pos=None):\n",
    "        self.panels[face].add(part_label, part, rel_pos, abs_pos)\n",
    "        return self\n",
    "\n",
    "    def add_screw(\n",
    "        self,\n",
    "        screw_size_category: str = \"m3\",\n",
    "        rel_pos = None,\n",
    "        abs_pos = None,\n",
    "        pos_error_margin = 0,\n",
    "        taper: TaperOptions = TaperOptions.NO_TAPER,\n",
    "        taper_rotation: float = 0.0,\n",
    "        screw_provider = DefaultFlatHeadScrewProvider,\n",
    "        counter_sunk_screw_provider = DefaultFlatHeadScrewProvider\n",
    "    ):\n",
    "        # TODO support lid != Face.BOTTOM\n",
    "\n",
    "        pos = None\n",
    "        if rel_pos == None and abs_pos == None:\n",
    "            raise ValueError(\"Either rel_pos or abs_pos must be set.\")\n",
    "        elif rel_pos == None:\n",
    "            pos = (\n",
    "                abs_pos[0] - self.size.inner_width/2,\n",
    "                abs_pos[1] - self.size.inner_length/2\n",
    "            )\n",
    "        elif abs_pos==None:\n",
    "            pos = rel_pos\n",
    "\n",
    "        screw = ScrewBlock(screw_provider, counter_sunk_screw_provider).build(\n",
    "            screw_size_category,\n",
    "            block_thickness=8,\n",
    "            taper=TaperOptions.Z_TAPER_ANGLE,\n",
    "            taper_rotation=taper_rotation\n",
    "        )\n",
    "        screw_wp = screw[\"block\"].translate([*pos, pos_error_margin])\n",
    "        self.screws.append(screw_wp)\n",
    "        return screw\n",
    "\n",
    "    def add_corner_lid_screws(self, lid_screws_thickness_error_margin):\n",
    "        # TODO support lid != Face.BOTTOM\n",
    "        screw_size_category = \"m3\"\n",
    "        screw_size = ScrewBlock().build(screw_size_category, 8)[\"size\"]\n",
    "        pw = self.size.inner_width\n",
    "        pl = self.size.inner_length\n",
    "        sw = screw_size[0]\n",
    "        sl = screw_size[1]\n",
    "        wt = self.size.wall_thickness\n",
    "        corners = [\n",
    "            ( (0+sw/2+wt,  0+sl/2+wt),    0 ),\n",
    "            ( (0+sw/2+wt,  pl-sl/2-wt),  90 ),\n",
    "            ( (pw-sw/2-wt, pl-sl/2-wt), 180 ),\n",
    "            ( (pw-sw/2-wt, 0+sl/2+wt),  270 )\n",
    "        ]\n",
    "        for c in corners:\n",
    "            screw_pos = c[0]\n",
    "            screw_rotation = c[1]\n",
    "            self.add_screw(\n",
    "                screw_size_category=screw_size_category,\n",
    "                abs_pos=screw_pos,\n",
    "                pos_error_margin=lid_screws_thickness_error_margin,\n",
    "                taper=TaperOptions.Z_TAPER_ANGLE,\n",
    "                taper_rotation=screw_rotation\n",
    "            )\n",
    "\n",
    "    def assemble(self, walls_explosion_factor=1.0, lid_panel_shift=0.0):\n",
    "        for panel in self.panels.values():\n",
    "            panel.assemble()\n",
    "\n",
    "        panels_assembly, panels_masks_assembly = self._build_panels_assembly(walls_explosion_factor, lid_panel_shift)\n",
    "        frame_assembly = self._build_frame_assembly(panels_masks_assembly)\n",
    "        lid_screws_assembly = self._build_lid_screws_assembly()\n",
    "\n",
    "        footprints_assembly = self._build_debug_assembly([(\"footprint_in\", \"I\"), (\"footprint_out\", \"O\")], walls_explosion_factor, lid_panel_shift)\n",
    "        holes_assembly = self._build_debug_assembly([(\"hole\", \"\")], walls_explosion_factor, lid_panel_shift)\n",
    "        other_debug_assembly = self._build_debug_assembly([(\"other\", \"\")], walls_explosion_factor, lid_panel_shift)\n",
    "\n",
    "        self.debug = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(footprints_assembly, name=\"Footprints\")\n",
    "                .add(holes_assembly, name=\"Holes\")\n",
    "                .add(other_debug_assembly, name=\"Others\")\n",
    "                .add(panels_masks_assembly, name=\"Panels masks\")\n",
    "        )\n",
    "        self.assembly = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(panels_assembly, name=\"Panels\")\n",
    "                .add(frame_assembly, name=\"Frame\")\n",
    "                .add(lid_screws_assembly, name=\"Lid screws\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "                .add(self.debug, name=\"Debug\")\n",
    "        )\n",
    "        self.printable_assembly = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(panels_assembly, name=\"Panels\")\n",
    "                .add(frame_assembly, name=\"Frame\")\n",
    "                .add(lid_screws_assembly, name=\"Lid screws\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "        )\n",
    "        return self\n",
    "\n",
    "    def _get_debug(self, panel: Panel, assembly_name=\"combined\"):\n",
    "        if assembly_name in panel.debug_assemblies:\n",
    "            return panel.debug_assemblies[assembly_name]\n",
    "        return None\n",
    "\n",
    "    def _build_panels_assembly(self, walls_explosion_factor, lid_panel_shift):\n",
    "        a = cq.Assembly(None)\n",
    "        masks_a = cq.Assembly(None)\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            panel: Panel = self.panels[face]\n",
    "            translated_mask = panel.mask.translate(position)\n",
    "            masks_a.add(translated_mask, name=(face.label + \" mask\"), color=cq.Color(0, 1, 0))\n",
    "            if face == Face.BOTTOM:\n",
    "                position = (position[0], position[1], position[2] - lid_panel_shift)\n",
    "            #if face == Face.BOTTOM:\n",
    "            #    continue\n",
    "            translated_panel = panel.panel.translate(explode(position, walls_explosion_factor))\n",
    "            a.add(translated_panel, name=face.label)\n",
    "        return (a, masks_a)\n",
    "\n",
    "    def _build_frame_assembly(self, panels_masks_assembly) -> cq.Workplane:\n",
    "        \"\"\"\n",
    "        Get the frame of the enclosure (the masks of the panels will be .cut during the assembly).\n",
    "        In this implemenmtation, it's only possible to remove the fillet\n",
    "        on the top and bottom of the enclosure (TODO: better implementation needed when lid_on_faces != [Face.BOTTOM] allowed),\n",
    "        but you can to override the method if you need something more custom (and feel free to contribute ;) )\n",
    "        \"\"\"\n",
    "        # TODO: when implementing the lid on other faces than BOTTOM, will have to remake that code better\n",
    "\n",
    "        wall_thickness = self.size.wall_thickness\n",
    "\n",
    "        shell_faces_filter = []\n",
    "        shell_size = [\n",
    "            self.size.inner_width - wall_thickness*2,\n",
    "            self.size.inner_length - wall_thickness*2,\n",
    "            self.size.inner_thickness - wall_thickness*2\n",
    "        ]\n",
    "        shell_translate_z = 0\n",
    "\n",
    "        if self.no_fillet_top:\n",
    "            shell_faces_filter.append(\"+Z\")\n",
    "            shell_size[2] = shell_size[2] + wall_thickness\n",
    "            shell_translate_z = shell_translate_z# + wall_thickness\n",
    "        if self.no_fillet_bottom:\n",
    "            shell_faces_filter.append(\"-Z\")\n",
    "            shell_size[2] = shell_size[2] + wall_thickness\n",
    "            shell_translate_z = shell_translate_z - wall_thickness\n",
    "\n",
    "        no_faces_filter = \"+Z and -Z\"  # as two faces cannot be true at once--cheeky way to avoid `.faces(\"\")`\n",
    "        shell_faces = no_faces_filter if len(shell_faces_filter) == 0 else \" or \".join(shell_faces_filter)\n",
    "\n",
    "        shell = (\n",
    "            cq.Workplane()\n",
    "                .box(*shell_size, centered=(True, True, False))\n",
    "                .faces(shell_faces)\n",
    "                .shell(wall_thickness)\n",
    "                .translate([0, 0, shell_translate_z])\n",
    "        )\n",
    "\n",
    "        return shell.cut(panels_masks_assembly.toCompound())\n",
    "\n",
    "    def _build_lid_screws_assembly(self):\n",
    "        a = cq.Assembly(None)\n",
    "        for idx, s in enumerate(self.screws):\n",
    "            a.add(s, name=f\"Screw #{idx}\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "        return a\n",
    "\n",
    "    def _cut_panels_masks_from_frame(self, frame: cq.Workplane) -> cq.Workplane:\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            panel: Panel = self.panels[face]\n",
    "            translated_mask = panel.mask.translate(position)\n",
    "            frame = frame.cut(translated_mask)\n",
    "        return frame\n",
    "\n",
    "    def _build_debug_assembly(self, assemblies_specs, walls_explosion_factor, lid_panel_shift):\n",
    "        a = cq.Assembly(None)\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            if face == Face.BOTTOM:\n",
    "                position = (position[0], position[1], position[2] - lid_panel_shift)\n",
    "            panel: Panel = self.panels[face]\n",
    "            for assembly_type, assembly_name_suffix in assemblies_specs:\n",
    "                debug_assembly = self._get_debug(panel, assembly_type)\n",
    "                if debug_assembly != None:\n",
    "                    translated_debug = debug_assembly.translate(explode(position, walls_explosion_factor))\n",
    "                    a.add(translated_debug, name=(f\"{face.label} {assembly_name_suffix}\"))\n",
    "        return a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "cd051dfe-443f-403a-90a1-1223af6db1cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "class AssemblyPart:\n",
    "    def __init__(self, workplane: cq.Workplane, name: str, color: cq.Color):\n",
    "        self.workplane: cq.Workplane = workplane\n",
    "        self.name: str = name\n",
    "        self.color: cq.Color = color\n",
    "\n",
    "    def as_assembly_add_parameters(self):\n",
    "        return (self.workplane, None, self.name, self.color)\n",
    "\n",
    "class DebugObjects:\n",
    "    class Footprint:\n",
    "        def __init__(self):\n",
    "            self.inside: cq.Workplane = None\n",
    "            self.outside: cq.Workplane = None\n",
    "\n",
    "    def __init__(self):\n",
    "        # Space taken by the component (anything: PCB, bolts, caps, etc.).\n",
    "        # Used for visualisation only.\n",
    "        self.footprint = DebugObjects.Footprint()\n",
    "\n",
    "        # Materialisation of the actual hole in the enclosure (e.g. a ~9.35mm extruded circle hole for a female jack).\n",
    "        # Used for visualisation only.\n",
    "        self.hole = None\n",
    "\n",
    "        self.others = {}\n",
    "\n",
    "class PartSize:\n",
    "    def __init__(self):\n",
    "        self.width: float = 0\n",
    "        self.length: float = 0\n",
    "        self.thickness: float = 0\n",
    "\n",
    "class Part:\n",
    "    def __init__(self):\n",
    "        self.part: cq.Workplane = None\n",
    "        self.mask: cq.Workplane = None\n",
    "        self.assembly_parts: List[AssemblyPart] = None\n",
    "\n",
    "        self.size = PartSize()\n",
    "        self.inside_footprint = None  # used by the layout builder  # TODO\n",
    "        self.outside_footprint = None  # used by the layout builder\n",
    "        self.inside_footprint_offset = None  # how far is it from 0,0\n",
    "        self.outside_footprint_offset = (0, 0)  # currently, it is assumed the center of the outside-facing side of the part is at 0,0\n",
    "\n",
    "        self.debug_objects = DebugObjects()\n",
    "\n",
    "    def assembly_parts_to_cq_assembly(self):\n",
    "        if self.assembly_parts is None:\n",
    "            return None\n",
    "        panel_assembly = cq.Assembly()\n",
    "        for part in self.assembly_parts:\n",
    "            panel_assembly.add(part.workplane, name=part.name, color=part.color)\n",
    "        return panel_assembly\n",
    "\n",
    "    def show(self):  # TODO delete\n",
    "        print(\"debug show() part \" + self.__class__.__name__ + \" - TODO delete\")\n",
    "\n",
    "    def validate(self):\n",
    "        print(\"VALIDATING CLASS: \" + self.__class__.__name__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "dad75adc-2809-4c19-8456-8e221e0badeb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (3/3)  0.41s\n"
     ]
    }
   ],
   "source": [
    "from enum import Enum\n",
    "\n",
    "class FanSize(Enum):\n",
    "    _40_MM = 1\n",
    "    _30_MM = 2\n",
    "    _25_MM = 3\n",
    "\n",
    "bp_size = 45\n",
    "enclosure_wall_thickness = 1.2\n",
    "\n",
    "base_plate = (\n",
    "    cq.Workplane(\"front\")\n",
    "        .box(bp_size, bp_size, enclosure_wall_thickness, centered=(True, True, False))\n",
    ")\n",
    "\n",
    "show(base_plate)\n",
    "\n",
    "@staticmethod\n",
    "def _get_fan_screws_blocks(\n",
    "    fan_size: FanSize,\n",
    "    block_thickness: float,\n",
    "    screw_block_taper_option: TaperOptions = TaperOptions.XY_TAPER,\n",
    "    screw_block_taper_rotation: float = 0,\n",
    "    screw_block_taper_on: str = \"1111\"  # should taper that specific screw block? same order as screws_pos\n",
    "):\n",
    "    screw = ScrewBlock().build(\"m2\", block_thickness, screw_hole_depth=block_thickness-1.2, taper=screw_block_taper_option, taper_rotation=screw_block_taper_rotation)\n",
    "    screw_no_taper = ScrewBlock().build(\"m2\", block_thickness, screw_hole_depth=block_thickness-1.2)\n",
    "\n",
    "    distance_between_screws = None  # center to center\n",
    "    if fan_size == FanSize._25_MM: distance_between_screws = 16.9 + 2.9\n",
    "    elif fan_size == FanSize._30_MM: distance_between_screws = 20.8 + 3.2\n",
    "    elif fan_size == FanSize._40_MM: distance_between_screws = 28.9 + 3.2\n",
    "    else: raise ValueError(\"Unknown FanSize\")\n",
    "\n",
    "    hdbs = distance_between_screws/2\n",
    "\n",
    "    screws_pos = [\n",
    "        (-hdbs,  hdbs),  # TR\n",
    "        ( hdbs,  hdbs),  # TL\n",
    "        ( hdbs, -hdbs),  # BL\n",
    "        (-hdbs, -hdbs),  # BR\n",
    "    ]\n",
    "\n",
    "    screws = cq.Assembly()\n",
    "    masks = cq.Assembly()\n",
    "    for idx, sp in enumerate(screws_pos):\n",
    "        current_screw = screw if screw_block_taper_on[idx] == \"1\" else screw_no_taper  # see apologies in constructor :D\n",
    "        screws.add(current_screw[\"block\"].translate([*sp, 0]))\n",
    "        masks.add(current_screw[\"mask\"].translate([*sp, 0]))\n",
    "\n",
    "    return {\n",
    "        \"screws\": screws.toCompound(),\n",
    "        \"masks\": masks.toCompound(),\n",
    "        #\"base_plate\": base_plate.translate([0, 0, -enclosure_wall_thickness])\n",
    "    }\n",
    "\n",
    "fan_screws = get_fan_screws_blocks(FanSize._25_MM, block_thickness=5)\n",
    "\n",
    "a = (\n",
    "    cq.Assembly()\n",
    "        .add(fan_screws[\"base_plate\"], name=\"base\")\n",
    "        .add(fan_screws[\"screws\"], name=\"Screws\")\n",
    "        .add(fan_screws[\"masks\"], name=\"Masks\")\n",
    ")\n",
    "\n",
    "show(a)\n",
    "\n",
    "from cadquery import exporters\n",
    "exporters.export(a.toCompound(), 'models/fan-40mm-v1.stl')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "7b6de967-b646-4613-bca3-32f952af5e66",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "from enum import Enum\n",
    "from typing import Union\n",
    "\n",
    "class FanSize(Enum):\n",
    "    _40_MM = 1\n",
    "    _30_MM = 2\n",
    "    _25_MM = 3\n",
    "\n",
    "class RectAirVentPart(Part):\n",
    "    \"\"\"\n",
    "    Class to make basic rectangular vents, with optional screws for fan.\n",
    "\n",
    "    Needs work. Hasn't been tested much besides the default parameters.\n",
    "    \"\"\"\n",
    "    def __init__(\n",
    "        self,\n",
    "        enclosure_wall_thickness,\n",
    "        width = 30,\n",
    "        length = 18,\n",
    "        thickness = 5,\n",
    "        margin = 1,\n",
    "        hole_angle = 25,\n",
    "        hole_width = 1.6,\n",
    "        distance_between_holes = 3,\n",
    "        taper = True,\n",
    "        taper_margin = 2,\n",
    "        taper_angle = 35,\n",
    "        with_fan_screws: Union[FanSize, None] = FanSize._25_MM,\n",
    "        fan_screws_taper_mode: TaperOptions = TaperOptions.XY_TAPER,\n",
    "        fan_screws_taper_rotation: float = 0,\n",
    "        fan_screws_taper_on: str = \"1100\"  # TODO cleanup one day; sorry future self, just want to be done with it :shrug:\n",
    "    ):\n",
    "        super().__init__()\n",
    "\n",
    "        # Board\n",
    "        board = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width, length, thickness, centered=(True, True, False))\n",
    "        )\n",
    "\n",
    "        # Add holes\n",
    "        single_hole = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(hole_width, length, thickness*6, centered=(True, True, False))\n",
    "                .translate([0, 0, -(thickness*3)])\n",
    "                .rotate((0, 0, 0), (0, 1, 0), hole_angle)\n",
    "        )\n",
    "\n",
    "        all_holes = cq.Assembly()\n",
    "        hole_x = 0\n",
    "        while hole_x < width/2:\n",
    "            all_holes.add(single_hole.translate([hole_x, 0, 0]))\n",
    "            all_holes.add(single_hole.translate([-hole_x, 0, 0]))\n",
    "            hole_x = hole_x + distance_between_holes\n",
    "\n",
    "        board = board.cut(all_holes.toCompound())\n",
    "\n",
    "        # Add frame\n",
    "        board = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width + margin*2, length + margin*2, thickness, centered=(True, True, False))\n",
    "                .cut(cq.Workplane(\"front\").box(width, length, thickness, centered=(True, True, False)))\n",
    "                .add(board)\n",
    "        )        \n",
    "\n",
    "        # Pyramid\n",
    "        if taper:\n",
    "            pyramid = (\n",
    "                cq.Workplane(\"front\")\n",
    "                    .rect(width + margin*2 + taper_margin*2, length + margin*2 + taper_margin*2)\n",
    "                    .extrude(30, taper=taper_angle)\n",
    "                    .cut(cq.Workplane(\"front\").rect(width + 4, length + 4).extrude(40).translate([0, 0, thickness - enclosure_wall_thickness]))\n",
    "                    .cut(cq.Workplane(\"front\").rect(width, length).extrude(thickness - enclosure_wall_thickness).translate([0, 0, 0]))\n",
    "                    .translate([0, 0, enclosure_wall_thickness])\n",
    "            )\n",
    "            board = board.add(pyramid)\n",
    "\n",
    "        # Fan screws\n",
    "        if with_fan_screws is not None:\n",
    "            fan_screws_a = RectAirVentPart._get_fan_screws_blocks(\n",
    "                with_fan_screws,\n",
    "                block_thickness=thickness-1,\n",
    "                screw_block_taper_option=fan_screws_taper_mode,\n",
    "                screw_block_taper_rotation=fan_screws_taper_rotation,\n",
    "                screw_block_taper_on=fan_screws_taper_on\n",
    "            )\n",
    "            fan_screws = fan_screws_a[\"screws\"].translate([0, 0, 1])\n",
    "            fan_masks = fan_screws_a[\"masks\"].translate([0, 0, 1])\n",
    "\n",
    "            board = board.cut(fan_masks).add(fan_screws)\n",
    "\n",
    "        # Mask & footprint\n",
    "        mask = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width, length, enclosure_wall_thickness, centered=(True, True, False))\n",
    "        )\n",
    "\n",
    "        self.part = board\n",
    "        self.mask = mask\n",
    "\n",
    "        self.size.width     = width\n",
    "        self.size.length    = length\n",
    "        self.size.thickness = thickness\n",
    "\n",
    "        self.inside_footprint = (self.size.width, self.size.length)\n",
    "        self.inside_footprint_offset = (0, 0)\n",
    "        self.outside_footprint = (self.size.width, self.size.length)\n",
    "        inside_footprint_thickness = 4\n",
    "        footprint_in = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(self.size.width, self.size.length)\n",
    "                .extrude(inside_footprint_thickness)\n",
    "                .translate([0, 0, enclosure_wall_thickness])\n",
    "        )\n",
    "        outside_footprint_thickness = 2\n",
    "        footprint_out = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(*self.outside_footprint)\n",
    "                .extrude(outside_footprint_thickness)\n",
    "                .translate([-0, 0, -outside_footprint_thickness])\n",
    "        )\n",
    "        self.debug_objects.footprint.inside  = footprint_in\n",
    "        self.debug_objects.footprint.outside = footprint_out\n",
    "        \n",
    "        self.debug_objects.hole = all_holes.toCompound()\n",
    "\n",
    "    @staticmethod\n",
    "    def _get_fan_screws_blocks(\n",
    "        fan_size: FanSize,\n",
    "        block_thickness: float,\n",
    "        screw_block_taper_option: TaperOptions = TaperOptions.XY_TAPER,\n",
    "        screw_block_taper_rotation: float = 0,\n",
    "        screw_block_taper_on: str = \"1111\"  # should taper that specific screw block? same order as screws_pos\n",
    "    ):\n",
    "        screw = ScrewBlock().build(\"m2\", block_thickness, screw_hole_depth=block_thickness-1.2, taper=screw_block_taper_option, taper_rotation=screw_block_taper_rotation)\n",
    "        screw_no_taper = ScrewBlock().build(\"m2\", block_thickness, screw_hole_depth=block_thickness-1.2)\n",
    "\n",
    "        distance_between_screws = None  # center to center\n",
    "        if fan_size == FanSize._25_MM: distance_between_screws = 16.9 + 2.9\n",
    "        elif fan_size == FanSize._30_MM: distance_between_screws = 20.8 + 3.2\n",
    "        elif fan_size == FanSize._40_MM: distance_between_screws = 28.9 + 3.2\n",
    "        else: raise ValueError(\"Unknown FanSize\")\n",
    "\n",
    "        hdbs = distance_between_screws/2\n",
    "\n",
    "        screws_pos = [\n",
    "            (-hdbs,  hdbs),  # TR\n",
    "            ( hdbs,  hdbs),  # TL\n",
    "            ( hdbs, -hdbs),  # BL\n",
    "            (-hdbs, -hdbs),  # BR\n",
    "        ]\n",
    "\n",
    "        screws = cq.Assembly()\n",
    "        masks = cq.Assembly()\n",
    "        for idx, sp in enumerate(screws_pos):\n",
    "            current_screw = screw if screw_block_taper_on[idx] == \"1\" else screw_no_taper  # see apologies in constructor :D\n",
    "            screws.add(current_screw[\"block\"].translate([*sp, 0]))\n",
    "            masks.add(current_screw[\"mask\"].translate([*sp, 0]))\n",
    "\n",
    "        return {\n",
    "            \"screws\": screws.toCompound(),\n",
    "            \"masks\": masks.toCompound(),\n",
    "            #\"base_plate\": base_plate.translate([0, 0, -enclosure_wall_thickness])\n",
    "        }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "bb2c98a5-5157-4730-bbab-62119ae4db39",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LEFT: adding part 'Vent'\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (3/3)  0.41s\n"
     ]
    }
   ],
   "source": [
    "        # hole_angle=25,\n",
    "        # hole_width=1.6,\n",
    "        # distance_between_holes=3,\n",
    "\n",
    "# vent = AirVentPart(2, width=30, length=25, thickness=5, with_fan_screws=FanSize._30_MM, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "vent = AirVentPart(2, width=25, length=20, thickness=5, with_fan_screws=FanSize._25_MM, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "# vent = AirVentPart(2, width=40, length=20, thickness=5, with_fan_screws=FanSize._25_MM, hole_angle=25, hole_width=1, distance_between_holes=1.5)\n",
    "# vent = AirVentPart(2, width=25, length=25, thickness=4, hole_angle=25, hole_width=1, distance_between_holes=1.5)\n",
    "# vent = AirVentPart(2, width=30, length=26, thickness=4, hole_angle=40, hole_width=2, distance_between_holes=4)\n",
    "# vent = AirVentPart(2, width=30, length=26, thickness=8, taper_margin=4, hole_angle=15, hole_width=1.2, distance_between_holes=2.1)\n",
    "# vent = AirVentPart(2, width=30, length=26, thickness=3, hole_angle=35, hole_width=0.6, distance_between_holes=1.35)\n",
    "\n",
    "p = Panel(Face.LEFT, 90, 36, 2)\n",
    "p.add(\"Vent\", vent, rel_pos=(0, 0))\n",
    "p.assemble()\n",
    "show(p.panel)\n",
    "# show_part(vent)\n",
    "# show(p.debug_assemblies[\"combined\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c88301d-6dc8-4446-b586-b5f8e0fe4ec8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "467c5ed7-f71a-46f9-8049-b20325f961b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "        self,\n",
    "        enclosure_wall_thickness,\n",
    "        width=30,\n",
    "        length=18,\n",
    "        thickness=4,\n",
    "        margin=1,\n",
    "        hole_angle=25,\n",
    "        hole_width=1.6,\n",
    "        distance_between_holes=3,\n",
    "        taper=True,\n",
    "        taper_margin=2,\n",
    "        taper_angle=45"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "id": "3b97947b-2cff-4fad-bbfb-69eaba4d9b4e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PyramidSupportPart(Part):\n",
    "    def __init__(self, enclosure_wall_thickness, support_height):\n",
    "        super().__init__()\n",
    "\n",
    "        base_size = 8\n",
    "        top_size = 5\n",
    "\n",
    "        # Board\n",
    "        board = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(base_size, base_size)\n",
    "                .extrude(support_height, taper=20)\n",
    "        )\n",
    "        board = board.add(\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(top_size, top_size)\n",
    "                .extrude(support_height)\n",
    "        )\n",
    "\n",
    "        self.part = board\n",
    "        self.mask = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(base_size, base_size, enclosure_wall_thickness, centered=(True, True, False))\n",
    "        )\n",
    "\n",
    "        self.size.width     = base_size\n",
    "        self.size.length    = base_size\n",
    "        self.size.thickness = support_height\n",
    "\n",
    "        self.inside_footprint = (self.size.width, self.size.length)\n",
    "        self.inside_footprint_offset = (0, 0)\n",
    "        self.outside_footprint = (0, 0)\n",
    "        self.debug_objects.footprint.inside  = board\n",
    "        self.debug_objects.footprint.outside = None\n",
    "        self.debug_objects.hole = None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 131,
   "id": "542856e8-2361-4316-a6c9-7999b9d5ac4f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (5/5)  0.02s\n"
     ]
    }
   ],
   "source": [
    "support = PyramidSupportPart(2, 17)\n",
    "\n",
    "show_part(support)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d32c7a9-015b-4ac7-9864-85a93f46f4b8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "id": "9ea3d1f9-f421-48eb-9b3a-630066e0daf3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LEFT: adding part 'Vent L'\n",
      "RIGHT: adding part 'Vent R'\n",
      "FRONT: adding part 'Vent F1'\n",
      "FRONT: adding part 'Vent F2'\n",
      "BACK: adding part 'Vent B1'\n",
      "BACK: adding part 'Vent B2'\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "TOP: adding part 'SPST 1'\n",
      "BOTTOM: adding part 'Support SPST'\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (68/68)  4.57s\n"
     ]
    }
   ],
   "source": [
    "from cq_enclosure_builder import PartFactory as pf\n",
    "\n",
    "vent_l = AirVentPart(2, width=30, length=25, thickness=5, with_fan_screws=FanSize._30_MM, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "vent_r = AirVentPart(2, width=30, length=25, thickness=5, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "\n",
    "vent_f1 = AirVentPart(2, width=40, length=20, thickness=5, with_fan_screws=FanSize._25_MM, hole_angle=25, hole_width=1, distance_between_holes=1.5)\n",
    "vent_b1 = AirVentPart(2, width=30, length=26, thickness=8, with_fan_screws=FanSize._25_MM, taper_margin=4, hole_angle=15, hole_width=1.2, distance_between_holes=2.1)\n",
    "\n",
    "vent_f2 = AirVentPart(2, width=30, length=26, thickness=4, hole_angle=40, hole_width=2, distance_between_holes=4)\n",
    "vent_b2 = AirVentPart(2, width=30, length=26, thickness=3, hole_angle=35, hole_width=0.6, distance_between_holes=1.35)\n",
    "\n",
    "enclosure = Enclosure(EnclosureSize(100, 60, 42, 2))\n",
    "enclosure.add_part_to_face(Face.LEFT, \"Vent L\", vent_l, rel_pos=(0, 0))\n",
    "enclosure.add_part_to_face(Face.RIGHT, \"Vent R\", vent_r, rel_pos=(0, 0))\n",
    "enclosure.add_part_to_face(Face.FRONT, \"Vent F1\", vent_f1, rel_pos=(-20, 0))\n",
    "enclosure.add_part_to_face(Face.FRONT, \"Vent F2\", vent_f2, rel_pos=(20, 0))\n",
    "enclosure.add_part_to_face(Face.BACK, \"Vent B1\", vent_b1, rel_pos=(-20, 0))\n",
    "enclosure.add_part_to_face(Face.BACK, \"Vent B2\", vent_b2, rel_pos=(20, 0))\n",
    "enclosure.add_part_to_face(Face.TOP, \"SPST 1\", pf.build_button(), abs_pos=(20, 30))\n",
    "enclosure.add_part_to_face(Face.BOTTOM, \"Support SPST\", support, abs_pos=(20, 30))\n",
    "enclosure.assemble()\n",
    "\n",
    "show(enclosure.assembly, hide_contains=[\"Masks\", \"FRONT\"])\n",
    "\n",
    "\n",
    "# from cadquery im/zzzzz"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 451,
   "id": "431c05f5-5f1e-450a-b853-29ec540bef7f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (2/2)  0.25s\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (3/3)  0.42s\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 452,
   "id": "1b624090-2b40-4042-ba1b-f5553bed6179",
   "metadata": {},
   "outputs": [],
   "source": [
    "screw = ScrewBlock().build(\"m2\", 3, screw_hole_depth=1)\n",
    "show(screw[\"block\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 363,
   "id": "281633aa-b6d1-4453-a96e-d7e0a737f078",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VALIDATING CLASS: Hdmi5InchJrp5015Part\n",
      "TOP: adding part 'Screen'\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "TOP: adding part 'SPST 1'\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "TOP: adding part 'SPST 2'\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "TOP: adding part 'SPST 3'\n",
      "VALIDATING CLASS: EncoderEc11Part\n",
      "TOP: adding part 'Encoder'\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "BACK: adding part 'Js0'\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "BACK: adding part 'Js1'\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "BACK: adding part 'Js2'\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "BACK: adding part 'Js3'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb0'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt0'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb1'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt1'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb2'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt2'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb3'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt3'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb4'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt4'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb5'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt5'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jb6'\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "BACK: adding part 'Jt6'\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "LEFT: adding part 'USB'\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "LEFT: adding part 'USB V'\n",
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "RIGHT: adding part 'USB C'\n",
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "RIGHT: adding part 'USB C'\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Unique name is required",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[363], line 27\u001b[0m\n\u001b[1;32m     21\u001b[0m enclosure\u001b[38;5;241m.\u001b[39madd_part_to_face(Face\u001b[38;5;241m.\u001b[39mRIGHT, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mUSB C\u001b[39m\u001b[38;5;124m\"\u001b[39m, pf\u001b[38;5;241m.\u001b[39mbuild_usb_c(), rel_pos\u001b[38;5;241m=\u001b[39m(\u001b[38;5;241m0\u001b[39m, \u001b[38;5;241m0\u001b[39m))\n\u001b[1;32m     24\u001b[0m \u001b[38;5;66;03m# TODO ADD VENTS! with or without screwable (heatset) fan - custom fins angle and size - print vertically \u001b[39;00m\n\u001b[0;32m---> 27\u001b[0m \u001b[43menclosure\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43massemble\u001b[49m\u001b[43m(\u001b[49m\u001b[43mwalls_explosion_factor\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m1.0\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlid_panel_shift\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m100\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     29\u001b[0m show(enclosure\u001b[38;5;241m.\u001b[39mprintable_assembly, hide_contains\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mgfg\u001b[39m\u001b[38;5;124m\"\u001b[39m])\n",
      "Cell \u001b[0;32mIn[362], line 136\u001b[0m, in \u001b[0;36mEnclosure.assemble\u001b[0;34m(self, walls_explosion_factor, lid_panel_shift)\u001b[0m\n\u001b[1;32m    134\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21massemble\u001b[39m(\u001b[38;5;28mself\u001b[39m, walls_explosion_factor\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1.0\u001b[39m, lid_panel_shift\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0.0\u001b[39m):\n\u001b[1;32m    135\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m panel \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpanels\u001b[38;5;241m.\u001b[39mvalues():\n\u001b[0;32m--> 136\u001b[0m         \u001b[43mpanel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43massemble\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    138\u001b[0m     panels_assembly, panels_masks_assembly \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_build_panels_assembly(walls_explosion_factor, lid_panel_shift)\n\u001b[1;32m    139\u001b[0m     frame_assembly \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_build_frame_assembly(panels_masks_assembly)\n",
      "Cell \u001b[0;32mIn[4], line 76\u001b[0m, in \u001b[0;36mPanel.assemble\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     74\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m part_to_add \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_parts_to_add:\n\u001b[1;32m     75\u001b[0m     part_obj \u001b[38;5;241m=\u001b[39m part_to_add[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpart\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n\u001b[0;32m---> 76\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_add_part_to_debug_assemblies\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpart_to_add\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     77\u001b[0m     wall \u001b[38;5;241m=\u001b[39m wall\u001b[38;5;241m.\u001b[39mcut(\n\u001b[1;32m     78\u001b[0m         part_obj\u001b[38;5;241m.\u001b[39mmask\u001b[38;5;241m.\u001b[39mtranslate([\u001b[38;5;241m*\u001b[39mpart_to_add[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpos\u001b[39m\u001b[38;5;124m\"\u001b[39m], \u001b[38;5;241m0\u001b[39m])\n\u001b[1;32m     79\u001b[0m     )\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m part_obj\u001b[38;5;241m.\u001b[39massembly_parts \u001b[38;5;241m!=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "Cell \u001b[0;32mIn[4], line 135\u001b[0m, in \u001b[0;36mPanel._add_part_to_debug_assemblies\u001b[0;34m(self, part_to_add)\u001b[0m\n\u001b[1;32m    133\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdebug_assemblies[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhole\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m cq\u001b[38;5;241m.\u001b[39mAssembly()\n\u001b[1;32m    134\u001b[0m     hole \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rotate_to_face(part\u001b[38;5;241m.\u001b[39mdebug_objects\u001b[38;5;241m.\u001b[39mhole\u001b[38;5;241m.\u001b[39mtranslate([\u001b[38;5;241m*\u001b[39mpart_pos, \u001b[38;5;241m0\u001b[39m]))\n\u001b[0;32m--> 135\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdebug_assemblies[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhole\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdebug_assemblies\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mhole\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43madd\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhole\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpart_label\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcolor\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcq\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mColor\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    136\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m part\u001b[38;5;241m.\u001b[39mdebug_objects\u001b[38;5;241m.\u001b[39mfootprint\u001b[38;5;241m.\u001b[39minside \u001b[38;5;241m!=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    137\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdebug_assemblies[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfootprint_in\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m==\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/cadquery/assembly.py:226\u001b[0m, in \u001b[0;36mAssembly.add\u001b[0;34m(self, arg, **kwargs)\u001b[0m\n\u001b[1;32m    223\u001b[0m     assy \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m(arg, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m    224\u001b[0m     assy\u001b[38;5;241m.\u001b[39mparent \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\n\u001b[0;32m--> 226\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43madd\u001b[49m\u001b[43m(\u001b[49m\u001b[43massy\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    228\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/cadquery/assembly.py:210\u001b[0m, in \u001b[0;36mAssembly.add\u001b[0;34m(self, arg, **kwargs)\u001b[0m\n\u001b[1;32m    208\u001b[0m name \u001b[38;5;241m=\u001b[39m kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mname\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;28;01mif\u001b[39;00m kwargs\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mname\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;28;01melse\u001b[39;00m arg\u001b[38;5;241m.\u001b[39mname\n\u001b[1;32m    209\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mobjects:\n\u001b[0;32m--> 210\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mUnique name is required\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    212\u001b[0m subassy \u001b[38;5;241m=\u001b[39m arg\u001b[38;5;241m.\u001b[39m_copy()\n\u001b[1;32m    214\u001b[0m subassy\u001b[38;5;241m.\u001b[39mloc \u001b[38;5;241m=\u001b[39m kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mloc\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;28;01mif\u001b[39;00m kwargs\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mloc\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;28;01melse\u001b[39;00m arg\u001b[38;5;241m.\u001b[39mloc\n",
      "\u001b[0;31mValueError\u001b[0m: Unique name is required"
     ]
    }
   ],
   "source": [
    "# ENCLOSURE_INNER_WIDTH =     220\n",
    "# ENCLOSURE_INNER_LENGTH =    150\n",
    "# ENCLOSURE_INNER_THICKNESS = 38\n",
    "# ENCLOSURE_WALLS_THICKNESS = 2\n",
    "\n",
    "# enclosure_size = EnclosureSize(ENCLOSURE_INNER_WIDTH, ENCLOSURE_INNER_LENGTH, ENCLOSURE_INNER_THICKNESS, ENCLOSURE_WALLS_THICKNESS)\n",
    "# enclosure = Enclosure(size=enclosure_size, no_fillet_bottom=True, no_fillet_top=True)\n",
    "# enclosure.add_part_to_face(Face.TOP, \"Screen\", pf.build_screen(), rel_pos=(0, -4))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 1\", pf.build_button(), abs_pos=(20, 30))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 2\", pf.build_button(), abs_pos=(20, 100))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 3\", pf.build_button(), abs_pos=(200, 30))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"Encoder\", pf.build_encoder(), abs_pos=(200, 100))\n",
    "# for i in range(0, 4):\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Js{i}\", pf.build_jack(part_type='3.5mm XXX'), abs_pos=(8, 4.5 + i*9))\n",
    "# for i in range(0, 7):\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Jb{i}\", pf.build_jack(), abs_pos=(24 + i*18, 10))\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Jt{i}\", pf.build_jack(), abs_pos=(24 + i*18, 18+9))\n",
    "# enclosure.add_part_to_face(Face.LEFT, \"USB\", pf.build_usb_a(), rel_pos=(0, 0))\n",
    "# enclosure.add_part_to_face(Face.LEFT, \"USB V\", pf.build_usb_a(orientation_vertical=True), rel_pos=(40, 0))\n",
    "# enclosure.add_part_to_face(Face.RIGHT, \"USB C\", pf.build_usb_c(), rel_pos=(0, 0))\n",
    "# enclosure.add_part_to_face(Face.RIGHT, \"USB C\", pf.build_usb_c(), rel_pos=(0, 0))\n",
    "\n",
    "# enclosure.assemble(walls_explosion_factor=1.0, lid_panel_shift=100)\n",
    "\n",
    "# show(enclosure.printable_assembly, hide_contains=[\"gfg\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 484,
   "id": "a4255c93-9209-4674-977a-6146bdf935b6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (2/2)  0.33s\n"
     ]
    }
   ],
   "source": [
    "ss = ScrewBlockX().m2(5, taper=TaperOptions.XY_TAPER, taper_rotation=0)\n",
    "\n",
    "show(ss[\"block\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe4bc8b3-c776-4548-becd-50c381a23ffb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
